# SPDX-License-Identifier: MIT
---
# Put the tasks for your role here.

- name: Set platform/version specific variables
  include_tasks: tasks/set_vars.yml

# Examples of some tasks:
- name: Ensure required packages are installed
  package:
    name: "{{ __ad_integration_packages }}"
    state: present

- name: Ensure required services are enabled and started
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ __ad_integration_services }}"

- name: Generate /etc/{{ __ad_integration_realmd_config }}
  template:
    src: "{{ __ad_integration_realmd_config }}.j2"
    dest: /etc/{{ __ad_integration_realmd_config }}
    backup: yes
    mode: 0400
  notify: ad_integration handler to restart services

- name: Flush handlers
  meta: flush_handlers

- name: Perform join operation
  shell: echo {{ ad_integration_password }} | realm join {{ ad_integration_realm }}
  when: not ansible_check_mode
